spring:
  application:
    name: wx
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/ashman-wx
server:
  port: 21002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:21000/eureka/
ashman:
  wx:
    app-id: wxfc19e603b952816b
    mode: compat
    server:
      token: ashman000odd
      encoding-a-e-s-key: 0X6nPs1kYqbxggNnD8QAjFBxM1g0LrvLvvkhfa7RVhY
      encoding-a-e-s-key-length: 43
  thread:
    pool:
      core-pool-size: 10
      maximum-pool-size: 20
      keep-alive-time: 0
      time-unit: milliseconds
      queue-size: 1024
logging:
  path: .